name: Publish Cloudflare Workers
on: push

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Cloudflare Workers CLI
              run: npm install -g wrangler

            - name: Build and publish Worker
              env:
                CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              run: |
                    npm install
                    wrangler deploy -c api-ctrlblk-dev.wrangler.toml

            - name: Build and publish Worker (release)
              if: github.ref == 'refs/heads/release'
              env:
                CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              run: |
                    npm install
                    wrangler deploy -c api-ctrlblk-com.wrangler.toml